name: Accounts
version: 1.3.0
description: Accounts plugins for Flextype.
icon: fas fa-users
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/accounts
bugs: https://github.com/flextype-plugins/accounts/issues
keywords: accounts, login, authentication
license: MIT

dependencies:
  flextype: 0.9.10
  site: '>=1.0.0'
  twig: '>=1.0.0'
  form: '>=1.0.0'
  jquery: '>=1.0.0'
  acl: '>=1.0.0'
  phpmailer: '>=1.0.0'
