name: Accounts
version: 1.1.1
description: Accounts plugins for Flextype.
icon: fas fa-users
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/accounts
bugs: https://github.com/flextype-plugins/accounts/issues
license: MIT

dependencies:
  flextype: 0.9.8
  site: '>=1.0.0'
  twig: '>=1.0.0'
  acl: '>=1.0.0'
  phpmailer: '>=1.0.0'
