name: Accounts
version: 1.8.0
description: Accounts plugins for Flextype.
icon:
  name: user
  set: "fontawesome|solid"
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/accounts
bugs: https://github.com/flextype-plugins/accounts/issues
keywords: accounts, login, authentication
license: MIT

dependencies:
  flextype: 0.9.15
  site: '>=1.0.0'
  twig: '>=2.0.0'
  form: '>=1.0.0'
  jquery: '>=1.0.0'
  acl: '>=1.0.0'
  phpmailer: '>=1.0.0'
