# enabled: true or false to disable the plugin
enabled: true

# Accounts plugin priority
priority: 80

# From email
from:
  email: support@flextype.org

registration:
  default_roles: user
  default_state: enabled
